// Mock data for laptops
export const laptops = [
    {
      id: "lenovo-ideapad-5-pro-16",
      name: "Lenovo IdeaPad 5 Pro 16",
      image: "/placeholder.svg?height=600&width=600",
      price: "$899.99",
      originalPrice: "$1,099.99",
      specs: {
        cpu: "AMD Ryzen 7 5800H",
        gpu: "NVIDIA GeForce RTX 3050 4GB",
        ram: "16GB DDR4 3200MHz",
        storage: "512GB NVMe SSD",
        display: '16" 2.5K (2560 x 1600) IPS, 120Hz',
        battery: "75Wh, Up to 12 hours",
      },
      benchmarks: {
        gaming: 7.5,
        productivity: 8.2,
        content: 7.8,
        battery: 8.5,
        display: 8.0,
        build: 7.9,
        value: 9.2,
        overall: 8.3,
      },
      detailedSpecs: {
        case: {
          weight: "1.9 kg (4.19 lbs)",
          dimensions: "356 x 251 x 17.5-18.4 mm",
          screenToBodyRatio: "86%",
          material: "Aluminum",
          color: "Storm Grey",
          maxOpenAngle: "180°",
          cooling: "Dual heat pipes, single fan",
          noiseLevel: "38dB under load",
        },
        display: {
          size: '16"',
          type: "IPS",
          refreshRate: "120Hz",
          resolution: "2560 x 1600",
          aspectRatio: "16:10",
          ppi: "189",
          brightness: "350 nits",
          colorGamut: {
            sRGB: "100%",
            adobeRGB: "75%",
            dciP3: "78%",
          },
          responseTime: "5ms",
          touchscreen: false,
          hdr: false,
        },
        battery: {
          capacity: "75Wh",
          chargeTime: "1.5 hours to full",
          type: "Lithium-polymer",
          replaceable: false,
          fastCharging: true,
          usbPD: true,
          chargerWattage: "100W",
          chargerWeight: "320g",
        },
        cpu: {
          name: "AMD Ryzen 7 5800H",
          baseFrequency: "3.2 GHz",
          turboFrequency: "4.4 GHz",
          cores: 8,
          threads: 16,
          cache: "16MB L3",
          integratedGPU: "AMD Radeon Graphics",
          process: "7nm",
          benchmarks: {
            geekbench6Single: 2345,
            geekbench6Multi: 11876,
            cinebenchR23Single: 1532,
            cinebenchR23Multi: 12456,
          },
        },
        gpu: {
          name: "NVIDIA GeForce RTX 3050",
          tgp: "80W",
          type: "Dedicated",
          process: "8nm",
          baseFrequency: "1057 MHz",
          boostFrequency: "1740 MHz",
          memory: "4GB GDDR6",
          memoryBus: "128-bit",
          memorySpeed: "12 Gbps",
          optimus: true,
          benchmarks: {
            wildlifeExtreme: 5678,
          },
        },
        ram: {
          capacity: "16GB",
          type: "DDR4",
          speed: "3200MHz",
          channels: 2,
          upgradeable: false,
          maxCapacity: "16GB",
          slots: 0,
        },
        storage: {
          capacity: "512GB",
          type: "NVMe SSD",
          interface: "PCIe 3.0 x4",
          upgradeable: true,
          slots: 1,
        },
        sound: {
          speakers: "2x 2W",
          dolbyAtmos: true,
          microphones: "Dual-array",
        },
        connectivity: {
          wifi: "Wi-Fi 6 (802.11ax)",
          bluetooth: "5.1",
          webcam: "1080p with privacy shutter",
          ports: {
            usba: 2,
            usbc: 2,
            thunderbolt: 0,
            hdmi: "1x HDMI 2.0",
            sdCard: "Full-size SD card reader",
            audio: "3.5mm combo jack",
            ethernet: false,
          },
          fingerprint: false,
          irCamera: true,
        },
        input: {
          keyboard: "Backlit keyboard",
          numpad: true,
          keyTravel: "1.5mm",
          touchpad: {
            size: "120 x 75 mm",
            surface: "Mylar",
            precision: true,
          },
        },
      },
      pros: [
        "Lightweight and compact for a powerful 16inch laptop",
        "Excellent value at it's price point",
        "Can do a wide variety of performance tasks well",
        "CPU and GPU are fed ample power and outperform other laptops with these parts",
      ],
      cons: [
        "Display's color gamut is not wide enough for some professional work",
        "Fan noise can get loud under heavy load",
        "No Thunderbolt support",
        "RAM is soldered and not upgradeable",
      ],
    },
    {
      id: "asus-rog-zephyrus-g14",
      name: "ASUS ROG Zephyrus G14",
      image: "/placeholder.svg?height=600&width=600",
      price: "$1,299.99",
      originalPrice: "$1,499.99",
      specs: {
        cpu: "AMD Ryzen 9 5900HS",
        gpu: "NVIDIA GeForce RTX 3060 6GB",
        ram: "16GB DDR4 3200MHz",
        storage: "1TB NVMe SSD",
        display: '14" QHD (2560 x 1440) IPS, 120Hz',
        battery: "76Wh, Up to 10 hours",
      },
      benchmarks: {
        gaming: 8.7,
        productivity: 8.9,
        content: 8.5,
        battery: 8.0,
        display: 8.5,
        build: 9.0,
        value: 8.5,
        overall: 8.7,
      },
      detailedSpecs: {
        case: {
          weight: "1.6 kg (3.53 lbs)",
          dimensions: "324 x 222 x 19.9 mm",
          screenToBodyRatio: "85%",
          material: "Magnesium-aluminum alloy",
          color: "Moonlight White / Eclipse Gray",
          maxOpenAngle: "180°",
          cooling: "Dual fans with liquid metal compound",
          noiseLevel: "40dB under load",
        },
        display: {
          size: '14"',
          type: "IPS",
          refreshRate: "120Hz",
          resolution: "2560 x 1440",
          aspectRatio: "16:9",
          ppi: "209",
          brightness: "300 nits",
          colorGamut: {
            sRGB: "100%",
            adobeRGB: "85%",
            dciP3: "90%",
          },
          responseTime: "3ms",
          touchscreen: false,
          hdr: false,
        },
        battery: {
          capacity: "76Wh",
          chargeTime: "1 hour to full",
          type: "Lithium-polymer",
          replaceable: false,
          fastCharging: true,
          usbPD: true,
          chargerWattage: "180W",
          chargerWeight: "300g",
        },
        cpu: {
          name: "AMD Ryzen 9 5900HS",
          baseFrequency: "3.0 GHz",
          turboFrequency: "4.6 GHz",
          cores: 8,
          threads: 16,
          cache: "16MB L3",
          integratedGPU: "AMD Radeon Graphics",
          process: "7nm",
          benchmarks: {
            geekbench6Single: 2567,
            geekbench6Multi: 12876,
            cinebenchR23Single: 1632,
            cinebenchR23Multi: 13456,
          },
        },
        gpu: {
          name: "NVIDIA GeForce RTX 3060",
          tgp: "60-80W",
          type: "Dedicated",
          process: "8nm",
          baseFrequency: "900 MHz",
          boostFrequency: "1802 MHz",
          memory: "6GB GDDR6",
          memoryBus: "192-bit",
          memorySpeed: "14 Gbps",
          optimus: true,
          benchmarks: {
            wildlifeExtreme: 7890,
          },
        },
        ram: {
          capacity: "16GB",
          type: "DDR4",
          speed: "3200MHz",
          channels: 2,
          upgradeable: true,
          maxCapacity: "40GB",
          slots: 1,
        },
        storage: {
          capacity: "1TB",
          type: "NVMe SSD",
          interface: "PCIe 3.0 x4",
          upgradeable: true,
          slots: 1,
        },
        sound: {
          speakers: "2x 2.5W with 2x 0.7W tweeters",
          dolbyAtmos: true,
          microphones: "Dual-array",
        },
        connectivity: {
          wifi: "Wi-Fi 6 (802.11ax)",
          bluetooth: "5.1",
          webcam: "None",
          ports: {
            usba: 2,
            usbc: 2,
            thunderbolt: 0,
            hdmi: "1x HDMI 2.0b",
            sdCard: "MicroSD card reader",
            audio: "3.5mm combo jack",
            ethernet: false,
          },
          fingerprint: true,
          irCamera: false,
        },
        input: {
          keyboard: "Backlit keyboard with 1.7mm travel",
          numpad: false,
          keyTravel: "1.7mm",
          touchpad: {
            size: "105 x 65 mm",
            surface: "Glass",
            precision: true,
          },
        },
      },
      pros: [
        "Extremely portable for a gaming laptop",
        "Excellent performance in a compact form factor",
        "Great battery life for a gaming laptop",
        "Premium build quality with magnesium alloy chassis",
      ],
      cons: ["No webcam", "Limited upgradeability", "Can get hot under sustained load", "No G-Sync support"],
    },
    {
      id: "dell-xps-15",
      name: "Dell XPS 15",
      image: "/placeholder.svg?height=600&width=600",
      price: "$1,799.99",
      originalPrice: "$1,999.99",
      specs: {
        cpu: "Intel Core i7-11800H",
        gpu: "NVIDIA GeForce RTX 3050 Ti 4GB",
        ram: "16GB DDR4 3200MHz",
        storage: "1TB NVMe SSD",
        display: '15.6" 4K (3840 x 2400) OLED Touch',
        battery: "86Wh, Up to 8 hours",
      },
      benchmarks: {
        gaming: 7.0,
        productivity: 9.0,
        content: 9.2,
        battery: 7.5,
        display: 9.5,
        build: 9.5,
        value: 7.8,
        overall: 8.6,
      },
      detailedSpecs: {
        case: {
          weight: "1.8 kg (4.0 lbs)",
          dimensions: "344.7 x 230.1 x 18 mm",
          screenToBodyRatio: "92.9%",
          material: "CNC machined aluminum",
          color: "Platinum Silver with Black carbon fiber interior",
          maxOpenAngle: "135°",
          cooling: "Dual fans with vapor chamber",
          noiseLevel: "42dB under load",
        },
        display: {
          size: '15.6"',
          type: "OLED",
          refreshRate: "60Hz",
          resolution: "3840 x 2400",
          aspectRatio: "16:10",
          ppi: "290",
          brightness: "400 nits",
          colorGamut: {
            sRGB: "100%",
            adobeRGB: "94%",
            dciP3: "100%",
          },
          responseTime: "0.2ms",
          touchscreen: true,
          hdr: true,
        },
        battery: {
          capacity: "86Wh",
          chargeTime: "2 hours to full",
          type: "Lithium-polymer",
          replaceable: false,
          fastCharging: true,
          usbPD: true,
          chargerWattage: "130W",
          chargerWeight: "390g",
        },
        cpu: {
          name: "Intel Core i7-11800H",
          baseFrequency: "2.3 GHz",
          turboFrequency: "4.6 GHz",
          cores: 8,
          threads: 16,
          cache: "24MB",
          integratedGPU: "Intel UHD Graphics",
          process: "10nm SuperFin",
          benchmarks: {
            geekbench6Single: 2456,
            geekbench6Multi: 12345,
            cinebenchR23Single: 1567,
            cinebenchR23Multi: 12789,
          },
        },
        gpu: {
          name: "NVIDIA GeForce RTX 3050 Ti",
          tgp: "45W",
          type: "Dedicated",
          process: "8nm",
          baseFrequency: "1035 MHz",
          boostFrequency: "1695 MHz",
          memory: "4GB GDDR6",
          memoryBus: "128-bit",
          memorySpeed: "12 Gbps",
          optimus: true,
          benchmarks: {
            wildlifeExtreme: 5234,
          },
        },
        ram: {
          capacity: "16GB",
          type: "DDR4",
          speed: "3200MHz",
          channels: 2,
          upgradeable: true,
          maxCapacity: "64GB",
          slots: 2,
        },
        storage: {
          capacity: "1TB",
          type: "NVMe SSD",
          interface: "PCIe 4.0 x4",
          upgradeable: true,
          slots: 2,
        },
        sound: {
          speakers: "2x 2.5W woofers, 2x 1.5W tweeters",
          dolbyAtmos: false,
          microphones: "Dual-array",
        },
        connectivity: {
          wifi: "Wi-Fi 6 (802.11ax)",
          bluetooth: "5.1",
          webcam: "720p HD with IR",
          ports: {
            usba: 0,
            usbc: 3,
            thunderbolt: 2,
            hdmi: 0,
            sdCard: "Full-size SD card reader",
            audio: "3.5mm combo jack",
            ethernet: false,
          },
          fingerprint: true,
          irCamera: true,
        },
        input: {
          keyboard: "Backlit keyboard",
          numpad: false,
          keyTravel: "1.3mm",
          touchpad: {
            size: "150 x 90 mm",
            surface: "Glass",
            precision: true,
          },
        },
      },
      pros: [
        "Stunning 4K OLED display with 100% DCI-P3 coverage",
        "Premium build quality with aluminum chassis",
        "Excellent keyboard and touchpad",
        "Great speakers for a laptop",
      ],
      cons: ["Expensive", "Limited port selection (no USB-A or HDMI)", "Average battery life", "Gets hot under load"],
    },
    {
      id: "hp-spectre-x360",
      name: "HP Spectre x360 14",
      image: "/placeholder.svg?height=600&width=600",
      price: "$1,399.99",
      originalPrice: "$1,599.99",
      specs: {
        cpu: "Intel Core i7-1165G7",
        gpu: "Intel Iris Xe Graphics",
        ram: "16GB LPDDR4X 4266MHz",
        storage: "1TB NVMe SSD",
        display: '13.5" 3K2K (3000 x 2000) OLED Touch',
        battery: "66Wh, Up to 14 hours",
      },
      benchmarks: {
        gaming: 5.0,
        productivity: 8.5,
        content: 8.0,
        battery: 9.0,
        display: 9.5,
        build: 9.5,
        value: 8.0,
        overall: 8.2,
      },
      detailedSpecs: {
        case: {
          weight: "1.36 kg (3.0 lbs)",
          dimensions: "298.5 x 220.1 x 17 mm",
          screenToBodyRatio: "90.3%",
          material: "CNC machined aluminum",
          color: "Nightfall Black / Poseidon Blue",
          maxOpenAngle: "360°",
          cooling: "Single fan with heat pipes",
          noiseLevel: "35dB under load",
        },
        display: {
          size: '13.5"',
          type: "OLED",
          refreshRate: "60Hz",
          resolution: "3000 x 2000",
          aspectRatio: "3:2",
          ppi: "267",
          brightness: "400 nits",
          colorGamut: {
            sRGB: "100%",
            adobeRGB: "96%",
            dciP3: "100%",
          },
          responseTime: "0.2ms",
          touchscreen: true,
          hdr: true,
        },
        battery: {
          capacity: "66Wh",
          chargeTime: "1.5 hours to full",
          type: "Lithium-polymer",
          replaceable: false,
          fastCharging: true,
          usbPD: true,
          chargerWattage: "65W",
          chargerWeight: "250g",
        },
        cpu: {
          name: "Intel Core i7-1165G7",
          baseFrequency: "2.8 GHz",
          turboFrequency: "4.7 GHz",
          cores: 4,
          threads: 8,
          cache: "12MB",
          integratedGPU: "Intel Iris Xe Graphics",
          process: "10nm SuperFin",
          benchmarks: {
            geekbench6Single: 2345,
            geekbench6Multi: 8765,
            cinebenchR23Single: 1456,
            cinebenchR23Multi: 6789,
          },
        },
        gpu: {
          name: "Intel Iris Xe Graphics",
          tgp: "28W",
          type: "Integrated",
          process: "10nm SuperFin",
          baseFrequency: "400 MHz",
          boostFrequency: "1300 MHz",
          memory: "Shared",
          memoryBus: "N/A",
          memorySpeed: "N/A",
          optimus: false,
          benchmarks: {
            wildlifeExtreme: 2345,
          },
        },
        ram: {
          capacity: "16GB",
          type: "LPDDR4X",
          speed: "4266MHz",
          channels: 2,
          upgradeable: false,
          maxCapacity: "16GB",
          slots: 0,
        },
        storage: {
          capacity: "1TB",
          type: "NVMe SSD",
          interface: "PCIe 4.0 x4",
          upgradeable: true,
          slots: 1,
        },
        sound: {
          speakers: "Quad speakers by Bang & Olufsen",
          dolbyAtmos: true,
          microphones: "Dual-array",
        },
        connectivity: {
          wifi: "Wi-Fi 6 (802.11ax)",
          bluetooth: "5.0",
          webcam: "720p HD with IR",
          ports: {
            usba: 1,
            usbc: 2,
            thunderbolt: 2,
            hdmi: 0,
            sdCard: "MicroSD card reader",
            audio: "3.5mm combo jack",
            ethernet: false,
          },
          fingerprint: true,
          irCamera: true,
        },
        input: {
          keyboard: "Backlit keyboard",
          numpad: false,
          keyTravel: "1.5mm",
          touchpad: {
            size: "115 x 76.6 mm",
            surface: "Glass",
            precision: true,
          },
        },
      },
      pros: [
        "Beautiful 3:2 OLED display",
        "Premium build quality and design",
        "Excellent battery life",
        "Versatile 2-in-1 form factor",
      ],
      cons: [
        "Limited gaming performance",
        "Fans can get noisy under load",
        "RAM is soldered and not upgradeable",
        "Expensive compared to non-convertible laptops",
      ],
    },
    {
      id: "acer-nitro-5",
      name: "Acer Nitro 5",
      image: "/placeholder.svg?height=600&width=600",
      price: "$899.99",
      originalPrice: "$999.99",
      specs: {
        cpu: "AMD Ryzen 7 5800H",
        gpu: "NVIDIA GeForce RTX 3060 6GB",
        ram: "16GB DDR4 3200MHz",
        storage: "512GB NVMe SSD",
        display: '15.6" FHD (1920 x 1080) IPS, 144Hz',
        battery: "57Wh, Up to 8 hours",
      },
      benchmarks: {
        gaming: 8.5,
        productivity: 7.8,
        content: 7.5,
        battery: 6.5,
        display: 7.5,
        build: 7.0,
        value: 9.0,
        overall: 7.8,
      },
      detailedSpecs: {
        case: {
          weight: "2.3 kg (5.07 lbs)",
          dimensions: "363.4 x 255 x 23.9 mm",
          screenToBodyRatio: "80%",
          material: "Plastic",
          color: "Black with red accents",
          maxOpenAngle: "140°",
          cooling: "Dual fans with quad exhaust ports",
          noiseLevel: "45dB under load",
        },
        display: {
          size: '15.6"',
          type: "IPS",
          refreshRate: "144Hz",
          resolution: "1920 x 1080",
          aspectRatio: "16:9",
          ppi: "141",
          brightness: "300 nits",
          colorGamut: {
            sRGB: "95%",
            adobeRGB: "65%",
            dciP3: "70%",
          },
          responseTime: "3ms",
          touchscreen: false,
          hdr: false,
        },
        battery: {
          capacity: "57Wh",
          chargeTime: "1.5 hours to full",
          type: "Lithium-ion",
          replaceable: false,
          fastCharging: true,
          usbPD: false,
          chargerWattage: "180W",
          chargerWeight: "540g",
        },
        cpu: {
          name: "AMD Ryzen 7 5800H",
          baseFrequency: "3.2 GHz",
          turboFrequency: "4.4 GHz",
          cores: 8,
          threads: 16,
          cache: "16MB L3",
          integratedGPU: "AMD Radeon Graphics",
          process: "7nm",
          benchmarks: {
            geekbench6Single: 2300,
            geekbench6Multi: 11500,
            cinebenchR23Single: 1500,
            cinebenchR23Multi: 12000,
          },
        },
        gpu: {
          name: "NVIDIA GeForce RTX 3060",
          tgp: "95W",
          type: "Dedicated",
          process: "8nm",
          baseFrequency: "900 MHz",
          boostFrequency: "1702 MHz",
          memory: "6GB GDDR6",
          memoryBus: "192-bit",
          memorySpeed: "14 Gbps",
          optimus: true,
          benchmarks: {
            wildlifeExtreme: 7500,
          },
        },
        ram: {
          capacity: "16GB",
          type: "DDR4",
          speed: "3200MHz",
          channels: 2,
          upgradeable: true,
          maxCapacity: "32GB",
          slots: 2,
        },
        storage: {
          capacity: "512GB",
          type: "NVMe SSD",
          interface: "PCIe 3.0 x4",
          upgradeable: true,
          slots: 2,
        },
        sound: {
          speakers: "Stereo speakers",
          dolbyAtmos: false,
          microphones: "Single",
        },
        connectivity: {
          wifi: "Wi-Fi 6 (802.11ax)",
          bluetooth: "5.0",
          webcam: "720p HD",
          ports: {
            usba: 3,
            usbc: 1,
            thunderbolt: 0,
            hdmi: "1x HDMI 2.0",
            sdCard: false,
            audio: "3.5mm combo jack",
            ethernet: "Gigabit Ethernet",
          },
          fingerprint: false,
          irCamera: false,
        },
        input: {
          keyboard: "4-zone RGB backlit keyboard",
          numpad: true,
          keyTravel: "1.6mm",
          touchpad: {
            size: "105 x 70 mm",
            surface: "Plastic",
            precision: true,
          },
        },
      },
      pros: [
        "Excellent gaming performance for the price",
        "Good thermal management",
        "Easily upgradeable RAM and storage",
        "144Hz display for smooth gaming",
      ],
      cons: [
        "Bulky and heavy design",
        "Average build quality with plastic chassis",
        "Mediocre battery life",
        "Display color accuracy could be better",
      ],
    },
  ]
  
  // Function to get a laptop by ID
  export function getLaptopById(id: string) {
    return laptops.find((laptop) => laptop.id === id) || null
  }
  
  // Function to search laptops by name
  export function searchLaptops(query: string) {
    if (!query) return []
    const lowerQuery = query.toLowerCase()
    return laptops.filter((laptop) => laptop.name.toLowerCase().includes(lowerQuery))
  }
  